### PR TITLE
Scion contrib

### PR DESCRIPTION
**Pull request by pszal**
Configuration and makefile for SCION's LWIP.

---

This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-lwip-contrib/1)

### CODE REVIEW

**Comment by pszal** [comment]
@kormat

**Comment by kormat** [comment]
When i build this, i get a ton of warnings of the form:

```
../../../../../scion-lwip/src/include/lwip/netif.h:128:49: warning: ‘struct netif’ declared inside parameter list [enabled by default]
 typedef void (*netif_status_callback_fn)(struct netif *netif);
                                                 ^
```

It seems like some definition is missing.

<details><summary>

<i>Previously, pszalach wrote…</i></summary>



> @kormat 
> </details>

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[ports/unix/proj/scion/lwipopts.h, line 62 [r2]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJoNEkaVsvViG7QE55E:-KJoNEkb-C0fsFwCaged:-86923612) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/87bd57a595690a13518bcc419ecd1ead1826f0ce/ports/unix/proj/scion/lwipopts.h#L62)):_

> ``` objc
>  * will be set to standard values. Override anything you dont like!
>  */
> #include "lwipopts.h"
> ```

Why does this file include itself?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-:-KJoQoYE3j4MIoYIb-yY:-1962044934)_

**Comment by pszal** [comment]
This is caused by the LWIP's code. `struct netif;` at the top of netif.h solves that, although I'm not sure whether we should fix LWIP's warnings.

<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> When i build this, i get a ton of warnings of the form:
> 
> ```
> ../../../../../scion-lwip/src/include/lwip/netif.h:128:49: warning: ‘struct netif’ declared inside parameter list [enabled by default]
>  typedef void (*netif_status_callback_fn)(struct netif *netif);
>                                                  ^
> ```
> 
> It seems like some definition is missing.
> </details>

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-:-KJtI6LtBE4aMWuJf_fJ:-1725462735)_

**Comment by pszal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[ports/unix/proj/scion/lwipopts.h, line 62 [r2]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJoNEkaVsvViG7QE55E:-KJtIZ0heIDZ_-y1BDGP:-487087489) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/87bd57a595690a13518bcc419ecd1ead1826f0ce/ports/unix/proj/scion/lwipopts.h#L62)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> Why does this file include itself?
> </details>
> Good question. That file bases on a LWIP's standard lwipopts, and I don't know why it was included. Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Comment by kormat** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[ports/unix/proj/scion/lwipopts.h, line 69 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu8x8j_NpcShkdq1FZ:-KJu8x8ko9ohsVXyWBYZ:-1349183486) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/lwipopts.h#L69)):_

> ``` objc
>  * allocation and deallocation.
>  */
> #define SYS_LIGHTWEIGHT_PROT            0
> ```

This file really needs a note to say which project it's based on, and then why each change was made.

---

_[ports/unix/proj/scion/Makefile, line 32 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9NztX4WybTak7U0b:-KJu9NztX4WybTak7U0c:369038128) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L32)):_

> ``` Makefile
> #
> 
> # Copyright 2016 ETH Zurich
> ```

Please note which makefile this is based on, so it's easy to check for changes.

---

_[ports/unix/proj/scion/Makefile, line 52 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9CbJ2Ud86C1Ak5M7:-KJu9CbJ2Ud86C1Ak5M8:1806869554) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L52)):_

> ``` Makefile
> #Set this to where you have the lwip core module checked out from CVS
> #default assumes it's a dir named lwip at the same level as the contrib module
> # TODO(PSz): change to sub/ after all parts are merged.
> ```

To make sure everything is working correctly, you should already be using sub/ in all 3 PRs.

---

_[ports/unix/proj/scion/unixlib.c, line 42 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9UCg4H8i5ZI9aM2S:-KJu9UCg4H8i5ZI9aM2T:1677501612) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/unixlib.c#L42)):_

> ``` C
>  * In particular, you should change the gateway, ipaddr, and netmask to be the values
>  * you would like the stack to use.
>  */
> ```

This also needs a note to say where it came from.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Comment by pszal** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[ports/unix/proj/scion/lwipopts.h, line 69 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu8x8j_NpcShkdq1FZ:-KJuPnJj4p0hvfBU-B_9:-499146009) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/lwipopts.h#L69)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> This file really needs a note to say which project it's based on, and then why each change was made.
> </details>
> Done.

---

_[ports/unix/proj/scion/Makefile, line 32 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9NztX4WybTak7U0b:-KJuPnuAgOCm9e_z8l4h:-499146009) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L32)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> Please note which makefile this is based on, so it's easy to check for changes.
> </details>
> Done.

---

_[ports/unix/proj/scion/Makefile, line 52 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9CbJ2Ud86C1Ak5M7:-KJuPoH0ojNl6E38Zm-i:-1606536740) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L52)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> To make sure everything is working correctly, you should already be using sub/ in all 3 PRs.
> </details>
> Let me do this after it is merged

---

_[ports/unix/proj/scion/unixlib.c, line 42 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9UCg4H8i5ZI9aM2S:-KJuPrqjQCbsVfLdOkyd:-499146009) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/unixlib.c#L42)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> This also needs a note to say where it came from.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Comment by kormat** [comment]
Reviewed 1 of 3 files at r5.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[ports/unix/proj/scion/Makefile, line 52 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9CbJ2Ud86C1Ak5M7:-KJuVRVKCZE_lxWBdlWs:-758144085) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L52)):_
<details><summary>

<i>Previously, pszalach wrote…</i></summary>



> Let me do this after it is merged
> </details>
> This is the wrong order to do things in.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Comment by pszal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[ports/unix/proj/scion/Makefile, line 52 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9CbJ2Ud86C1Ak5M7:-KKDIiQz8f6NoAMkwhSC:-499146009) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L52)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> This is the wrong order to do things in.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Comment by kormat** [comment]
Reviewed 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[ports/unix/proj/scion/Makefile, line 52 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9CbJ2Ud86C1Ak5M7:-KKDNJz2C5cc89jTMZ_u:471731567) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L52)):_
<details><summary>

<i>Previously, pszalach wrote…</i></summary>



> Done.
> </details>
> Please remove the TODO :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Comment by kormat** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-:-KKDPH0CmuyiGZggSZXL:1417088721)_

**Comment by pszal** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[ports/unix/proj/scion/Makefile, line 52 [r4]](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1#-KJu9CbJ2Ud86C1Ak5M7:-KKEB0ClAvJ8SSl6Vvws:-499146009) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/1ea15881833dbf46ee11a9be50594805d0e8babc/ports/unix/proj/scion/Makefile#L52)):_
<details><summary>

<i>Previously, kormat (Stephen Shirley) wrote…</i></summary>



> Please remove the TODO :)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/1)_

**Pull request merged**
