### PR TITLE
Switch to using SCION-specific checksum.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-lwip-contrib/11)

### CODE REVIEW

**Comment by pszal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ports/unix/proj/scion/Makefile, line 63 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/11#-KjrwbI3AqkZR1m078Di:-KjrwbI3AqkZR1m078Dj:bjrq78n) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/521e0baaafb67b01456d674ae937bce49d4aa5af/ports/unix/proj/scion/Makefile#L63)):*
> ```Makefile
> 
> CFLAGS:=$(CFLAGS) \
> 	-I$(LWIPDIR)/include -I$(LWIPARCH)/include -I$(LWIPDIR)/include/scion -I$(LWIPDIR)/include/ipv4 -I$(LWIPDIR) -I$(SCIONLIB) -I.
> ```

is that ipv4 include still needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/11)*

**Comment by pszal** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/11#-:-Kjrwgx3JW5qqZ9LjZZE:bnfp4nl)*

**Comment by kormat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ports/unix/proj/scion/Makefile, line 63 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/11#-KjrwbI3AqkZR1m078Di:-KjrxxTejQqapT4owOc1:bpv2zy2) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/521e0baaafb67b01456d674ae937bce49d4aa5af/ports/unix/proj/scion/Makefile#L63)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

is that ipv4 include still needed?
</blockquote></details>

Just tested - TCP needs it for ICMP.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/11)*

**Comment by pszal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/11)*

**Pull request merged**
