### PR TITLE
TCP settings

### PR DESCRIPTION
**Pull request by pszal**
TCP setting that give ~3 times better performance than the default one.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-lwip-contrib/9)

### CODE REVIEW

**Comment by pszal** [comment]
@kormat

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ports/unix/proj/scion/lwipopts.h, line 256 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/9#-KYwVm9auuZqPR0iQEbn:-KYwVm9bcwlNB3pLBVYt:b-n1lffv) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/9770a3e2fdede619c205aebc7afb524878e7848c/ports/unix/proj/scion/lwipopts.h#L256)):*
> ```objc
> #define LWIP_TCP                        1
> 
> /* TCP settings */
> ```

It would be nice to have a comment regarding the origin of these constants or the rationale for choosing them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/9)*

**Comment by pszal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ports/unix/proj/scion/lwipopts.h, line 256 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/9#-KYwVm9auuZqPR0iQEbn:-KYx9e3R6P2B31ja2Vce:bsj78nn) ([raw file](https://github.com/netsec-ethz/scion-lwip-contrib/blob/9770a3e2fdede619c205aebc7afb524878e7848c/ports/unix/proj/scion/lwipopts.h#L256)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

It would be nice to have a comment regarding the origin of these constants or the rationale for choosing them.
</blockquote></details>

All these parameter values are chosen empirically, but I put comments with default values.
After some more testing seems that `TCP_MSS` and `TCP_SND_BUF` are dominant for the perfomance in our scenario, thus I left other options with default values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/9)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-lwip-contrib/9#-:-KYxMFXjxBIdQz1gkZSe:bnfp4nl)*

**Review by klausman — APPROVED** [review]

**Pull request merged**
